<script>
  // Generated by ChatGPT,
  // Prompt: Generate a tailwind-css and svelte layout for PC app (electron), naming layout,
  //  I want a sidebar (open/close), a top toolbar and a workspace. The layout should adapt to the window size.

  let isSidebarOpen = true;
  const toggleSidebar = () => {
    isSidebarOpen = !isSidebarOpen;
  };

  import { PanelRightOpen, PanelRightClose } from 'lucide-svelte';
</script>

<div class="flex h-screen flex-col">
  <!-- Top Toolbar -->
  <div class="flex items-center bg-gray-800 p-2 text-white">
    <button class="mr-4 rounded bg-gray-700 p-2 hover:bg-gray-600" on:click={toggleSidebar}>
      {#if isSidebarOpen}
        <PanelRightOpen />
      {:else}
        <PanelRightClose />
      {/if}
    </button>
    <slot name="toolbar"><h1 class="text-xl font-bold">PC App Layout</h1></slot>
  </div>

  <div class="flex flex-1 overflow-hidden">
    <!-- Sidebar -->
    <div
      class={`transition-all ${isSidebarOpen ? 'w-64' : 'w-0'} resize-x overflow-hidden bg-gray-200`}
    >
      <!-- Added resize-x -->
      {#if isSidebarOpen}
        <slot name="sidebar"></slot>
      {/if}
    </div>

    <!-- Workspace -->
    <div class="flex-1 overflow-auto bg-white p-4">
      <slot name="workspace">
        <h2 class="mb-4 text-2xl font-bold">Workspace</h2>
        <p>This is the main workspace area where the content goes.</p>
      </slot>
    </div>
  </div>
</div>
